"""empty message

Revision ID: 51c8b1fdfeed
Revises: 
Create Date: 2020-06-04 13:14:05.979931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c8b1fdfeed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redditors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('page', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('train_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('features', sa.ARRAY(sa.Float()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reddit_memes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('reddit_id', sa.String(length=20), nullable=False),
    sa.Column('subreddit', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('meme_text', sa.String(length=10000), nullable=True),
    sa.Column('template', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('upvote_ratio', sa.Float(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('features', sa.ARRAY(sa.Float()), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['redditors.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reddit_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('subreddit', sa.String(length=50), nullable=False),
    sa.Column('time_delta', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('num_in_bottom', sa.Integer(), nullable=False),
    sa.Column('num_in_top', sa.Integer(), nullable=False),
    sa.Column('shitposter_index', sa.Float(), nullable=False),
    sa.Column('highest_upvotes', sa.Integer(), nullable=False),
    sa.Column('hu_score', sa.Float(), nullable=False),
    sa.Column('lowest_ratio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['redditors.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_scores')
    op.drop_table('reddit_memes')
    op.drop_table('train_data')
    op.drop_table('templates')
    op.drop_table('redditors')
    # ### end Alembic commands ###
