"""empty message

Revision ID: b4652e6eea82
Revises: d6fc8ef0391f
Create Date: 2020-06-03 20:28:59.041233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4652e6eea82'
down_revision = 'd6fc8ef0391f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_data', sa.Column('end_page', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('train_data', 'end_page')
    # ### end Alembic commands ###
