"""empty message

Revision ID: ba392afb91f8
Revises: 
Create Date: 2020-04-30 21:19:40.020310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba392afb91f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_memedata():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_memes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reddit_id', sa.String(length=20), nullable=False),
    sa.Column('subreddit', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=False),
    sa.Column('media', sa.String(length=200), nullable=False),
    sa.Column('meme_text', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('upvote_ratio', sa.Float(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.Column('nsfw', sa.String(length=10), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reddit_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=False),
    sa.Column('subreddit', sa.String(length=50), nullable=False),
    sa.Column('td', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('num_in_bottom', sa.Integer(), nullable=False),
    sa.Column('num_in_top', sa.Integer(), nullable=False),
    sa.Column('shitposter_index', sa.Float(), nullable=False),
    sa.Column('highest_upvotes', sa.Integer(), nullable=False),
    sa.Column('hu_score', sa.Float(), nullable=False),
    sa.Column('lowest_ratio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('imgflip_page', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_memedata():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    op.drop_table('reddit_scores')
    op.drop_table('reddit_memes')
    # ### end Alembic commands ###


def upgrade_sitedata():
    pass


def downgrade_sitedata():
    pass


def upgrade_hivedata():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memehub_community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorperm', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('isPost', sa.Boolean(), nullable=False),
    sa.Column('isHive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorperm', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('community', sa.String(length=200), nullable=False),
    sa.Column('isPost', sa.Boolean(), nullable=False),
    sa.Column('isHive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_hivedata():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votable')
    op.drop_table('memehub_community')
    # ### end Alembic commands ###

