"""empty message

Revision ID: d6fc8ef0391f
Revises: 53abcafab1e7
Create Date: 2020-06-03 19:49:57.604145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fc8ef0391f'
down_revision = '53abcafab1e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('features', sa.ARRAY(sa.Float()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('train_data')
    # ### end Alembic commands ###
